homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam

frontend:

http:

updater:

discovery:

conversation:

history:

logbook:

sun:

emulated_hue:
  host_ip: 192.168.1.249
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - light
    - scene

arduino:
  port: /dev/arduino

device_tracker:
  - platform: tplink
    host: !secret tpl_ip
    username: !secret tpl_user
    password: !secret tpl_password

remote:
  - platform: harmony
    name: Huiskamer
    host: 192.168.1.30

automation: !include_dir_list config/automation/
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
scene: !include config/scenes.yaml
light: !include config/lights.yaml
