homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam

frontend:

http:

updater:

discovery:

conversation:

history:

logbook:

sun:

arduino:
  port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

automation: !include_dir_list config/automation/
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
scene: !include config/scenes.yaml
light: !include config/lights.yaml
