homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam

frontend:

http:

updater:

discovery:

media_player:
  - platform: cast

conversation:

history:

config:

influxdb:
  host: 127.0.0.1
  username: hass
  password: hass58

logbook:

sun:

customize:
  scene.huiskamer_langzaam_normaal:
    hide_entity: true
  scene.huiskamer_licht_langzaam_uit:
    hide_entity: true
  scene.huiskamer_tv:
    hide_entity: true
  sensor.toon:
    hide_entity: true

arduino:
  port: /dev/arduino

device_tracker:
  - platform: tplink
    host: !secret tpl_ip
    username: !secret tpl_user
    password: !secret tpl_password

remote:
  - platform: harmony
    name: Huiskamer
    host: 192.168.1.30
    activity: "Watch TV"
    scan_interval: 10

automation: !include_dir_list config/automation/
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
scene: !include config/scenes.yaml
light: !include config/lights.yaml
switch: !include config/switch.yaml
