homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include config/customize.yaml

recorder:
  purge_interval: 1
  purge_keep_days: 14
  db_url: !secret db_url

http:
  api_password: !secret api_password
  base_url: !secret base_url
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - !secret trusted_home_network

influxdb:
  host: 127.0.0.1
  username: !secret influxdb_user
  password: !secret influxdb_password

frontend:

map:

updater:

discovery:

conversation:

history:

logbook:

sun:

media_player:
  - platform: cast

toon:
  username: !secret toon_username
  password: !secret toon_password

climate:
  platform: toon

google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  exposed_domains:
    - switch
    - light
    - group
    - scene
    - climate

tts:
  - platform: google

mysensors:
  gateways:
    - device: '192.168.1.5'
      tcp_port: 5003
      persistence_file: !secret mysensors_persistence
  persistence: true
  version: 2.0

device_tracker:
  - platform: owntracks_http
    waypoint_whitelist:
      - danny

remote:
  - platform: harmony
    name: Harmony Hub
    activity: "Watch TV"
    scan_interval: 10

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 400

    #input_boolean:
    #  guest_switch:
    #    name: Guest switch
    #    initial: off

automation: !include_dir_list config/automation/
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
scene: !include config/scenes.yaml
light: !include config/lights.yaml
notify: !include config/notify.yaml
switch: !include config/switches.yaml
