
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include config/customize.yaml

frontend:

http:
  api_password: !secret api_password
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - !secret trusted_home_network

updater:

discovery:

media_player:
  - platform: cast

conversation:

history:

config:

influxdb:
  host: 127.0.0.1
  username: !secret influxdb_user
  password: !secret influxdb_password

toon:
  username: !secret toon_username
  password: !secret toon_password

google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  exposed_domains:
    - switch
    - light
    - group

logbook:

sun:

mysensors:
  gateways:
    - device: '192.168.1.5'
      tcp_port: 5003
      persistence_file: !secret mysensors_persistence
  persistence: true
  version: 1.5

device_tracker:
  - platform: asuswrt
    mode: ap
    host: !secret asus_ip
    username: !secret asus_user
    password: !secret asus_password
    track_new_devices: no

remote:
  - platform: harmony
    name: Huiskamer
    host: 192.168.1.30
    activity: "Watch TV"
    scan_interval: 10

automation: !include_dir_list config/automation/
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
scene: !include config/scenes.yaml
light: !include config/lights.yaml
notify: !include config/notify.yaml
switch: !include config/switches.yaml
