homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: metric
  time_zone: Europe/Amsterdam

frontend:

http:

updater:

discovery:

conversation:

history:

logbook:

sun:

arduino:
  port: /dev/ttyUSB0

media_player:
  - platform: samsungtv
    name: tv huiskamer
    host: 192.168.1.10


automation: !include_dir_list config/automation/
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
scene: !include config/scenes.yaml
light: !include config/lights.yaml
