title: De lieverds

views:
  - title: Example
    cards:
      - type: markdown
        title: Lovelace
        content: >
          Welkom hoor

  - title: Basis
    path: basis
    cards:
      - type: entity-button
        entity: scene.huiskamer_langzaam_normaal
        name: Huis
        icon: mdi:home
