title: De lieverds

views:
  - title: Example
    cards:
      - type: markdown
        title: Lovelace
        content: >
          Welkom hoor

  - title: Basis
    path: basis
    cards:
      - type: entity-filter
        entries:
          - device_tracker.danny_oneplus5t
          - device_tracker.anna_oneplus3
        state_filter:
          - "home"
        card:
          type: glance
          title: Thuis
