title: De lieverds

views:
  - title: Example
    cards:
      - type: markdown
        title: Lovelace
        content: >
          Welkom hoor

  - title: Basis
    path: basis
    cards:
      - type: entity-button
        entity: scene.huiskamer_langzaam_normaal
        tap_action: call-service
        service: scene.turn_on
        name: Huis
        icon: mdi:home
      - type: thermostat
        entity: climate.toon_thermostat
        name: Temperatuur
