title: Huis
resources:
  - url: /local/button-card.js
    type: module
  - url: /local/light-card.js
    type: js
  - url: /local/gauge-card.js?v=2
    type: js
views:
  - title: Huiskamer
    cards:
      - type: entities
        title: Lichten
        entities:
          - entity: light.oma_lamp
            name: Oma Lamp
          - entity: light.lamp_bank
            name: Bank Lamp
      - type: custom:button-card
        entity: group.all_lights
        icon: mdi:home
        color: auto
  - title: Tablet
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: HUIS
            entity: switch.huiskamer_light_switch
            icon: mdi:home
            color: auto
            color_type: card
          - type: custom:button-card
            name: GEZELLIG
            icon: mdi:glass-wine
            action: service
            service:
              domain: scene
              action: turn_on
              data:
                entity_id: scene.huiskamer_mfb
          - type: custom:button-card
            name: NORMAAL
            icon: mdi:ceiling-light
            action: service
            service:
              domain: scene
              action: turn_on
              data:
                entity_id: scene.huiskamer_normaal
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: KEUKEN RADAR
            icon: mdi:radar
            color: auto
            color_type: card
            entity: automation.keuken_lamp_aan_bij_beweging
          - type: custom:button-card
            name: GAST
            icon: mdi:home-account
            color: auto
            color_type: card
            entity: switch.guest_switch
      - type: horizontal-stack
        cards:
          - type: custom:gauge-card
            title: Licht sensor
            entity: sensor.light_sensor_1_0
            min: 0
            max: 100
            scale: '40px'
            severity:
              - green: 40
              - red: 0
              - amber: 25
          - type: custom:gauge-card
            title: Licht Sensor Batt
            entity: sensor.lightlevel_battery
            min: 60
            max: 100
            scale: '40px'
            severity:
              - green: 80
              - red: 70
              - amber: 75
