alias: planten water notificatie
hide_entity: false
trigger:
  - platform: numeric_state
    entity_id: sensor.plant_sensor_6_0
    below: 200
action:
  service: tts.google_say
  entity_id: media_player.mfb
  data:
    message: 'De planten hebben weer water nodig.'

