alias: 001.email_battery_level
hide_entry: false
trigger:
  - platform: numeric_state
    entry_id: sensor.lightlevel_battery
    below: 93
action:
  service: notify.email_danny
  data:
    title: 'Low Battery level'
    message: 'Light level metering device needs a battery charge'

