alias: 001 - Lichten aan als het donker is
hide_entity: True
trigger:
  - platform: numeric_state
    entity_id: sensor.light_sensor_1_0
    below: 65
  - platform: time
    after: '06:45'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_langzaam_normaal
