alias: 001.email_battery_level
hide_entity: true
trigger:
  - platform: numeric_state
    entity_id: sensor.lightlevel_battery
    below: 65
action:
  service: notify.email_danny
  data:
    title: 'Low Battery level'
    message: 'Light level metering device needs a battery charge'

