alias: 001 - Lichten als het donker is
hide_entity: True
trigger:
  - platform: numeric_state
    entity_id: sensor.light_sensor
    below: 500
  - platform: time
    after: '06:45'
    before: '01:15'
condition: use_trigger_values
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_langzaam_normaal
