alias: 002 - Lichten uit nt
hide_entity: True
trigger:
  - platform: numeric_state
    entity_id: sensor.light_sensor_1_0
    above: 18
condition:
  - condition: and
    conditions:
      - condition: time
        after: '07:00'
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.guest_switch
            state: 'off'
          - condition: state
            entity_id: group.all_devices
            state: 'not_home'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_licht_langzaam_uit
