alias: 001 - Lichten uit
hide_entity: True
trigger:
  - platform: numeric_state
    entity_id: sensor.light_sensor_1_0
    above: 67
condition:
  - condition: time
    after: '07:00'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_licht_langzaam_uit
