alias: Keuken lamp aan bij beweging
trigger:
  - platform: state
    enitity_id: binary_sensor.keuken_arduino_7_2
    to: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: switch.keuken_arduino_7_0
