alias: Licht uit
trigger:
  platform: state
  entity_id: binary_sensor.keuken_sensor_202_2
  to: 'off'
  for:
    seconds: 10
action:
  service: switch.turn_off
  entity_id:
    - switch.keuken_sensor_202_3
    - binary_sensor.keuken_sensor_202_2
