alias: Licht aan bij beweging
trigger:
  platform: state
  entity_id: binary_sensor.keuken_sensor_202_2
  from: 'off'
  to: 'on'
action:
  service: switch.turn_on
  entity_id: switch.keuken_sensor_202_3
