- alias: Licht aan bij beweging
  trigger:
    platform: state
    entity_id: binary_sensor.keuken_sensor_202_2
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.keuken_sensor_202_3

- alias: Licht uit
  trigger:
    platform: state
    entity_id: binary_sensor.keuken_sensor_202_2
    to: 'off'
    for:
      seconds: 30
  action:
    service: homeassistant.turn_off
    entity_id: switch.keuken_sensor_202_3
