alias: start radio
trigger:
  - platform: state
    entity_id: input_select.radio_station
action:
  - service: media_player.play_media
    data_template:
      entity_id: media_player.mfb
      media_content_id: >
        {% if is_state("input_select.radio_station", "Radio 1") %}
          http://icecast.omroep.nl/radio1-bb-mp3
        {%- elif is_state("input_select.radio_station", "Radio 2") %}
          http://icecast.omroep.nl/radio2-bb-mp3
        {%- elif is_state("input_select.radio_station", "3FM") %}
          http://icecast.omroep.nl/3fm-bb-mp3
        {%- elif is_state("input_select.radio_station", "3FM Alt") %}
          http://icecast.omroep.nl/3fm-alternative-mp3
        {%- elif is_state("input_select.radio_station", "Radio 4") %}
          http://icecast.omroep.nl/radio4-bb-mp3
        {%- elif is_state("input_select.radio_station", "BNR") %}
          http://icecast-bnr-cdp.triple-it.nl/bnr_mp3_96_04
        {% else %}
          none
        {% endif %}
      media_content_type: 'audio/mp4'
