huiskamer:
  name: Huiskamer
  entities:
    - light.hoek_lamp
    - light.keuken_tafel
    - light.lamp_bank
    - light.oma_lamp

keuken:
  name: Keuken
  entities:
    - light.led_strip_keuken_201_5
