platform: limitlessled
bridges:
  - host: 192.168.1.3
    version: 5
    groups:
    - number: 1
      name: Lamp bank
      type: rgbw
    - number: 2
      name: Keuken tafel
      type: rgbw
    - number: 3
      name: Hoek lamp
      type: rgbw
    - number: 1
      name: Oma lamp
      type: white

