- platform: limitlessled
  bridges:
    - host: 192.168.1.3
      version: 5
      port: 8899
      groups:
      - number: 1
        name: lamp_bank
        type: rgbw
        fade: on
      - number: 2
        name: keuken_tafel
        type: rgbw
        fade: on
      - number: 3
        name: hoek_lamp
        type: rgbw
        fade: on
      - number: 1
        name: oma_lamp
        type: white
        fade: on

