platform: limitlessled
bridges:
  - host: 192.168.1.3
    version: 5
    port: 8899
    groups:
    - number: 1
      name: Lamp bank
      type: rgbw
      fade: on
    - number: 2
      name: Keuken tafel
      type: rgbw
      fade: on
    - number: 3
      name: Hoek lamp
      type: rgbw
      fade: on
    - number: 1
      name: Oma lamp
      type: white
      fade: on

