- name: huiskamer normaal
  entities:
    light.hoek_lamp:
      state: on
      transition: 10
      brightness: 255
      rgb_color: [ 255, 214, 0  ]
    light.keuken_tafel:
      state: on
      transition: 10
      brightness: 255
      rgb_color: [ 255, 214, 0  ]
    light.lamp_bank:
      state: on
      transition: 10
      brightness: 255
      rgb_color: [ 255, 214, 0  ]
    light.oma_lamp:
      state: on
      brightness: 200
- name: huiskamer tv
  hide_entiry: True
  entities:
    light.hoek_lamp:
      state: on
      transition: 30
      brightness: 200
      rgb_color: [ 29, 42, 224]
    light.keuken_tafel:
      state: on
      transition: 30
      brightness: 200
      rgb_color: [ 229, 119, 9 ]
    light.lamp_bank:
      state: on
      transition: 30
      brightness: 180
      rgb_color: [ 229, 119, 9 ]
    light.oma_lamp:
      state: on
      brightness: 70
- name: huiskamer mfb
  hide_entiry: True
  entities:
    light.hoek_lamp:
      state: on
      transition: 30
      brightness: 200
      rgb_color: [ 16, 209, 43]
    light.keuken_tafel:
      state: on
      transition: 30
      brightness: 200
      rgb_color: [ 229, 119, 9 ]
    light.lamp_bank:
      state: on
      transition: 30
      brightness: 200
      rgb_color: [ 229, 119, 9 ]
    light.oma_lamp:
      state: on
      brightness: 100
- name: huiskamer veel licht
  entities:
    light.hoek_lamp:
      state: on
      brightness: 255
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.keuken_tafel:
      state: on
      brightness: 255
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.lamp_bank:
      state: on
      brightness: 255
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.oma_lamp:
      state: on
      brightness: 255
- name: huiskamer langzaam normaal
  entities:
    light.hoek_lamp:
      state: on
      transition: 30
      brightness: 255
      rgb_color: [ 255, 214, 0  ]
    light.keuken_tafel:
      state: on
      transition: 30
      brightness: 255
      rgb_color: [ 255, 214, 0  ]
    light.lamp_bank:
      state: on
      transition: 30
      brightness: 255
      rgb_color: [ 255, 214, 0  ]
    light.oma_lamp:
      state: on
      brightness: 175
- name: huiskamer licht uit
  entities:
    light.hoek_lamp:
      state: off
    light.keuken_tafel:
      state: off
    light.lamp_bank:
      state: off
    light.oma_lamp:
      state: off
- name: huiskamer licht langzaam uit
  entities:
    light.hoek_lamp:
      state: off
      transition: 60
    light.keuken_tafel:
      state: off
      transition: 60
    light.lamp_bank:
      state: off
      transition: 60
    light.oma_lamp:
      state: off
- name: Toon Comfort
  entities:
    switch.toon_prog_comfort: on
- name: Toon Sleep
  entities:
    switch.toon_prog_comfort: off
- name: Toon Home
  entities:
    switch.toon_prog_thuis: on
- name: Toon Away
  entities:
    switch.toon_prog_thuis: off
