- name: huiskamer normaal
  entities:
    light.hoek_lamp:
      state: on
      transition: 10
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.keuken_tafel:
      state: on
      transition: 10
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.lamp_bank:
      state: on
      transition: 10
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.oma_lamp:
      state: on
      brightness_pct: 100
- name: huiskamer tv
  entities:
    light.hoek_lamp:
      state: on
      transition: 30
      brightness_pct: 80
      rgb_color: [ 29, 42, 224]
    light.keuken_tafel:
      state: on
      transition: 30
      brightness_pct: 80
      rgb_color: [ 229, 119, 9 ]
    light.lamp_bank:
      state: on
      transition: 30
      brightness_pct: 60
      rgb_color: [ 229, 119, 9 ]
    light.oma_lamp:
      state: on
      brightness_pct: 30
- name: huiskamer mfb
  entities:
    light.hoek_lamp:
      state: on
      transition: 30
      brightness_pct: 80
      rgb_color: [ 16, 209, 43]
    light.keuken_tafel:
      state: on
      transition: 30
      brightness_pct: 80
      rgb_color: [ 229, 119, 9 ]
    light.lamp_bank:
      state: on
      transition: 30
      brightness_pct: 80
      rgb_color: [ 229, 119, 9 ]
    light.oma_lamp:
      state: on
      brightness_pct: 40
- name: huiskamer veel licht
  entities:
    light.hoek_lamp:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.keuken_tafel:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.lamp_bank:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.oma_lamp:
      state: on
      brightness_pct: 100
- name: huiskamer langzaam normaal
  entities:
    light.hoek_lamp:
      state: on
      transition: 60
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.keuken_tafel:
      state: on
      transition: 60
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.lamp_bank:
      state: on
      transition: 60
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.oma_lamp:
      state: on
      brightness_pct: 70
- name: huiskamer licht uit
  entities:
    light.hoek_lamp:
      state: off
    light.keuken_tafel:
      state: off
    light.lamp_bank:
      state: off
    light.oma_lamp:
      state: off
- name: huiskamer licht langzaam uit
  entities:
    light.hoek_lamp:
      state: off
      transition: 60
    light.keuken_tafel:
      state: off
      transition: 60
    light.lamp_bank:
      state: off
      transition: 60
    light.oma_lamp:
      state: off
- name: keuken normaal
  entities:
    light.led_strip_keuken_201_5:
      state: on
      transition: 60
      brightness_pct: 100
      rgb_color: [ 255, 214, 0 ]
- name: keuken koken
  entities:
    light.led_strip_keuken_201_5:
      state: on
      transition: 30
      brightness_pct: 100
      rgb_color: [ 255, 255, 255 ]
- name: keuken uit
  entities:
    light.led_strip_keuken_201_5:
      state: off
      transition: 60
- name: Toon Comfort
  entities:
    switch.toon_prog_comfort: on
- name: Toon Sleep
  entities:
    switch.toon_prog_comfort: off
- name: Toon Home
  entities:
    switch.toon_prog_thuis: on
- name: Toon Away
  entities:
    switch.toon_prog_thuis: off
