- name: huiskamer normaal
  entities:
    light.hoek_lamp:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.keuken_tafel:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.lamp_bank:
      state: on
      brightness_pct: 99
      rgb_color: [ 255, 214, 0  ]
    light.oma_lamp:
      state: on
      brightness_pct: 100
    light.keuken_arduino_7_1:
      state: on
      brightness_pct: 70
      rgb_color: [ 255, 64, 0 ]
- name: huiskamer tv
  entities:
    light.hoek_lamp:
      state: on
      brightness_pct: 80
      rgb_color: [ 29, 42, 224]
    light.keuken_tafel:
      state: on
      brightness_pct: 80
      rgb_color: [ 229, 119, 9 ]
    light.lamp_bank:
      state: on
      brightness_pct: 60
      rgb_color: [ 229, 119, 9 ]
    light.oma_lamp:
      state: on
      brightness_pct: 30
    light.keuken_arduino_7_1:
      state: on
      brightness_pct: 50
      rgb_color: [ 255, 64, 0 ]
- name: huiskamer mfb
  entities:
    light.hoek_lamp:
      state: on
      brightness_pct: 80
      rgb_color: [ 16, 209, 43]
    light.keuken_tafel:
      state: on
      brightness_pct: 80
      rgb_color: [ 229, 119, 9 ]
    light.lamp_bank:
      state: on
      brightness_pct: 80
      rgb_color: [ 229, 119, 9 ]
    light.oma_lamp:
      state: on
      brightness_pct: 40
    light.keuken_arduino_7_1:
      state: on
      brightness_pct: 50
      rgb_color: [ 255, 64, 0 ]
- name: huiskamer veel licht
  entities:
    light.hoek_lamp:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.keuken_tafel:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.lamp_bank:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 255, 255  ]
      color_temp: 200
    light.oma_lamp:
      state: on
      brightness_pct: 100
    light.keuken_arduino_7_1:
      state: on
      brightness_pct: 50
      rgb_color: [ 255, 64, 0 ]
- name: huiskamer langzaam normaal
  entities:
    light.hoek_lamp:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.keuken_tafel:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.lamp_bank:
      state: on
      brightness_pct: 100
      rgb_color: [ 255, 214, 0  ]
    light.oma_lamp:
      state: on
      brightness_pct: 70
    light.keuken_arduino_7_1:
      state: on
      brightness_pct: 50
      rgb_color: [ 255, 64, 0 ]
- name: huiskamer licht uit
  entities:
    light.hoek_lamp:
      state: off
    light.keuken_tafel:
      state: off
    light.lamp_bank:
      state: off
    light.oma_lamp:
      state: off
    light.keuken_arduino_7_1:
      state: off
- name: huiskamer licht langzaam uit
  entities:
    light.hoek_lamp:
      state: off
      transition: 60
    light.keuken_tafel:
      state: off
      transition: 60
    light.lamp_bank:
      state: off
      transition: 60
    light.oma_lamp:
      state: off
    light.keuken_arduino_7_1:
      state: off
