- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: template
  sensors:
    huiskamer:
      value_template: '{{ states.remote.huiskamer.attributes.current_activity }}'
      friendly_name: 'Huiskamer'

- platform: template
  sensors:
    lightlevel_battery:
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.light_sensor_1_0.attributes.battery_level }}'
