- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: arduino
  pins:
    0:
      name: Light Sensor

- platform: template
  sensors:
    huiskamer:
      value_template: '{{ states.remote.huiskamer.attributes.current_activity }}'
      friendly_name: 'Huiskamer'
