- platform: template
  switches:
    huiskamer:
      turn_on:
        service: switch.turn_on
        entity_id: scene.huiskamer_langzaam_normaal
      turn_off:
        service: switch.turn_on
        entity_id: scene.huiskamer_licht_langzaam_uit
