# The following swith set Toon to "Comfort" with the oncmd and sets Toon to "Sleep" with the offcmd.
- platform: command_line
  switches:
    toon_prog_comfort_sleep:
      command_on: "python3 /srv/hass/.homeassistant/scripts/toonclient.py -C 0 -D /srv/hass/.toon.ini"
      command_off: "python3 /srv/hass/.homeassistant/scripts/toonclient.py -C 2 -D /srv/hass/.toon.ini"

# The following swith set Toon to "Home" with the oncmd and sets Toon to "Away" with the offcmd.      
- platform: command_line
  switches:
    toon_prog_home_away:
      command_on: "python3 /srv/hass/.homeassistant/scripts/toonclient.py -C 1 -D /srv/hass/.toon.ini"
      command_off: "python3 /srv/hass/.homeassistant/scripts/toonclient.py -C 3 -D /srv/hass/.toon.ini"
