- platform: template
  switches:
    huiskamer_light_switch:
      value_template: "{{ is_state('group.all_lights', 'on') }}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.huiskamer_langzaam_normaal
      turn_off:
        service: scene.turn_on
        entity_id: scene.huiskamer_licht_langzaam_uit

- platform: template
  switches:
    guest_switch:
      value_template: "{{ is_state('device_tracker.guest_at_home', 'home') }}"
      turn_on:
        service: device_tracker.see
        data:
          dev_id: guest_at_home
          location_name: "home"
      turn_off:
        service: device_tracker.see
        data:
          dev_id: guest_at_home
          location_name: "not_home"
