- platform: template
  switches:
    huiskamer:
      value_template: "{{ is_state('group.all_lights', 'on') }}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.huiskamer_langzaam_normaal
      turn_off:
        service: scene.turn_on
        entity_id: scene.huiskamer_licht_langzaam_uit
