alias: Lichten aan als het donker is en niet thuis
hide_entity: False
trigger:
  - platform: numeric_state
    entity_id: sensor.huiskamer_licht
    below: 12
  - platform: time
    at: '06:45'
condition:
  condition: state
  entity_id: group.all_persons
  state: 'not_home'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_langzaam_normaal
