alias: 001 - Lichten aan als het donker is
hide_entity: True
trigger:
  - platform: numeric_state
    entity_id: sensor.light_sensor_1_0
    below: 62
  - platform: time
    at: '06:45'
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'home'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_langzaam_normaal
