alias: 001 - Lichten aan als het donker is
hide_entity: False
trigger:
  - platform: numeric_state
    entity_id: sensor.huiskamer_licht
    below: 29
  - platform: time
    at: '06:45'
  - platform: state
    entity_id: group.all_persons
    from: 'not_home'
    to: 'home'
condition:
  condition: state
  entity_id: group.all_persons
  state: 'home'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_langzaam_normaal
