alias: Lichten uit
hide_entity: False
trigger:
  - platform: numeric_state
    entity_id: sensor.huiskamer_licht
    above: 32
condition:
  - condition: and
    conditions:
      - condition: time
        after: '07:00'
      - condition: state
        entity_id: group.all_persons
        state: 'home'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_licht_langzaam_uit
