alias: "MFB uit"
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.cast_to_mfb
    from: 'on'
    to: 'off'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_normaal
