alias: "MFB stekker aan"
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.mfb_keuken
    from: 'off'
action:
  service: homeassistant.turn_on
  entity_id: switch.tradfri_stekker_1
