alias: Notificate licht intensiteit battery
hide_entity: true
trigger:
  - platform: numeric_state
    entity_id: sensor.lightlevel_battery
    below: 65
action:
  service: tts.google_say
  entity_id: media_player.mfb
  data:
    message: 'De batterij in de licht intensiteit meter is bijna op.'

