alias: verwarming uit nacht
hide_entity: False
trigger:
  - platform: time
    at: '23:30'
  - platform: time
    at: '02:30'
condition:
  condition: state
  entity_id: group.all_persons
  state: 'home'
action:
  service: climate.set_temperature
  data:
    entity_id: climate.toon_thermostat
    temperature: 17
