alias: verwarming home
hide_entity: False
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.toon_thermostat
      temperature: 21
