alias: verwarming uit nacht
hide_entity: True
trigger:
  - platform: time
    at: '23:30'
  - platform: time
    at: '02:30'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'home'
action:
  service: climate.set_temperature
  data:
    entity_id: climate.toon_van_eneco
    temperature: 17
