- name: "Keuken Radar"
  platform: mqtt
  state_topic: "keuken/motion/status"
- name: "Deurbel"
  platform: mqtt
  state_topic: "deur/bell/pressed"
  payload_on: "ON"
  payload_off: "OFF"
- platform: template
  sensors:
    garagedeur:
      friendly_name: "Garage Open"
      value_template: "{{ is_state('switch.garage_deur', 'on') }}"
