- platform: mqtt
  name: "Keuken RGB LED"
  state_topic: "keuken/rgb1/light/status"
  command_topic: "keuken/rgb1/light/switch"
  brightness_state_topic: "keuken/rgb1/brightness/status"
  brightness_command_topic: "keuken/rgb1/brightness/set"
  rgb_state_topic: "keuken/rgb1/rgb/status"
  rgb_command_topic: "keuken/rgb1/rgb/set"
  state_value_template: "{{ value_json.state }}"
  brightness_value_template: "{{ value_json.brightness }}"
  rgb_value_template: "{{ value_json.rgb | join(',') }}"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
- platform: limitlessled
  bridges:
    - host: 192.168.1.3
      version: 5
      port: 8899
      groups:
        - number: 1
          name: lamp_bank
          type: rgbw
          fade: on
        - number: 2
          name: keuken_tafel
          type: rgbw
          fade: on
        - number: 3
          name: hoek_lamp
          type: rgbw
          fade: on
        - number: 1
          name: oma_lamp
          type: white
          fade: on
