- platform: buienradar
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windspeed
    - pressure
    - winddirection
    - humidity

- platform: time_date
  display_options:
    - time
    - date
    - date_time
    - time_date
    - time_utc
    - beat

- platform: mqtt
  name: "Huiskamer temperatuur"
  state_topic: "huiskamer/temperature/status"
  unit_of_measurement: '°C'

- platform: mqtt
  name: "Huiskamer vochitgheid"
  state_topic: "huiskamer/humidty/status"
  unit_of_measurement: '%'

- platform: mqtt
  name: "Huiskamer licht"
  state_topic: "huiskamer/lightlevel/status"
  unit_of_measurement: '%'

- platform: template
  sensors:
    huiskamer_tv:
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      friendly_name: 'Huiskamer TV'

- platform: mqtt
  name: "Tradfri stekker 1"
  state_topic: "zigbee2mqtt/0x000b3cfffeff0caf"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"
