- platform: buienradar
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windspeed
    - pressure
    - winddirection
    - humidity

- platform: template
  sensors:
    huiskamer:
      value_template: '{{ states.remote.huiskamer.attributes.current_activity }}'
      friendly_name: 'Huiskamer'

- platform: template
  sensors:
    lightlevel_battery:
      unit_of_measurement: '%'
      value_template: '{{ states.sensor.light_sensor_1_0.attributes.battery_level }}'

- platform: time_date
  display_options:
    - time
    - date
    - date_time
    - time_date
    - time_utc
    - beat
