- platform: template
  switches:
    huiskamer_light_switch:
      value_template: "{{ is_state('group.all_lights', 'on') }}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.huiskamer_langzaam_normaal
      turn_off:
        service: scene.turn_on
        entity_id: scene.huiskamer_licht_langzaam_uit
    guest_switch:
      value_template: "{{ is_state('device_tracker.guest_at_home', 'home') }}"
      turn_on:
        service: device_tracker.see
        data:
          dev_id: guest_at_home
          location_name: "home"
      turn_off:
        service: device_tracker.see
        data:
          dev_id: guest_at_home
          location_name: "not_home"

- platform: mqtt
  name: "Keuken LED"
  command_topic: "keuken/led/light/switch"
  state_topic: "keuken/led/light/status"
  payload_on: "ON"
  payload_off: "OFF"

- platform: mqtt
  name: "Garage Deur"
  command_topic: "garage/relay/switch"
  state_topic: "garage/relay/status"
  state_on: "ON"
  state_off: "OFF"
  payload_on: "ON"
  payload_off: "ON"
