- platform: template
  switches:
    huiskamer_light_switch:
      value_template: "{{ is_state('group.all_lights', 'on') }}"
      turn_on:
        service: scene.turn_on
        entity_id: scene.huiskamer_langzaam_normaal
      turn_off:
        service: scene.turn_on
        entity_id: scene.huiskamer_licht_langzaam_uit
    guest_switch:
      value_template: "{{ is_state('device_tracker.guest_at_home', 'home') }}"
      turn_on:
        service: device_tracker.see
        data:
          dev_id: guest_at_home
          location_name: "home"
      turn_off:
        service: device_tracker.see
        data:
          dev_id: guest_at_home
          location_name: "not_home"
    tv_kijken:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Watch TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
    chromecast_kijken:
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Chromecast Huiskamer') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Chromecast Huiskamer'
      turn_off:
        service: remote.turn_on
        data:
          entiry_id: remote.harmony_hub
          activity: 'PowerOff'

- platform: mqtt
  name: "Garage Deur"
  command_topic: "garage/relay/switch"
  state_topic: "garage/relay/status"
  state_on: "ON"
  state_off: "OFF"
  payload_on: "ON"
  payload_off: "ON"

- platform: mqtt
  name: "Tradfri stekker 1"
  state_topic: "zigbee2mqtt/0x000b3cfffeff0caf"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/0x000b3cfffeff0caf/set"
