alias: 001 - Lichten aan bij zonsondergang
hide_entity: True
trigger:
  platform: sun
  event: sunset
  offset: "-01:30:00"
action:
  service: scene.turn_on
  entity_id: scene.huiskamer_langzaam_normaal
